services:
  app:
    image: ${DOCKER_HUB_USERNAME}/smartspend:dev 
    container_name: smartspend-app
    restart: always
    ports:
      - "443:443"

    environment:
      SPRING_PROFILES_ACTIVE: docker

      # --- AIVEN ---
      SPRING_DATASOURCE_URL: jdbc:mysql://${AIVEN_DB_HOST}:${AIVEN_DB_PORT}/${AIVEN_DB_NAME}?sslMode=${AIVEN_DB_SSL_MODE}&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${AIVEN_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${AIVEN_DB_PASSWORD}
      
      # --- SEGURIDAD ---
      JWT_SECRET: ${JWT_SECRET}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
