server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD:smartspend}
    key-alias: smartspend-ssl
    key-store-type: PKCS12

spring:
  datasource:
    url: jdbc:h2:mem:smartspend;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.springframework.boot.web.embedded.tomcat: INFO
