spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartspend?createDatabaseIfNotExist=true
    username: smartspend
    password: smartspend
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
