name: CI - Basic Quality Check

on:
  push:
    branches:
      - "feature/**"
      - "fix/**"

env:
  SPRING_PROFILES_ACTIVE: dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build backend and run tests (dev profile)
        working-directory: backend
        run: mvn clean verify -B

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Start frontend server 
        working-directory: frontend 
        run: nohup npm run start &

      - name: Wait for frontend
        run: sleep 20
