name: CI - Basic Quality Check

on:
  push:
    branches:
      - "feature/**"
      - "fix/**"

env:
  SPRING_PROFILES_ACTIVE: dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: dev

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Chrome for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Build backend
        working-directory: backend
        run: mvn clean install -DskipTests -B

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Start backend server
        working-directory: backend
        run: |
          nohup mvn spring-boot:run -Dspring-boot.run.profiles=dev > backend.log 2>&1 &
          echo "Waiting for backend to start..."
          sleep 30

      - name: Start frontend server
        run: |
          npx http-server ./frontend/dist/frontend/browser -p 4200 &
          echo "Waiting for frontend to start..."
          sleep 10

      - name: Run unit and integration tests
        working-directory: backend
        run: mvn -B test -Dtest="!*ui*"

      - name: Run UI tests
        working-directory: backend
        run: mvn -B test -Dtest="*ui*"
